[package]
name = "rupg-index"
description = "The B-tree, hash, GIN, GiST, SP-GiST and BRIN access methods and their operator class interface."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
publish = false

[dependencies]

[lints]
workspace = true
