[package]
name = "rupg-wasm"
description = "The WebAssembly module and its storage on the OPFS."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
publish = false

[dependencies]

[lints]
workspace = true
