//! The generated files of `rupg-sql`: the parse tables from `gram.y` and the keyword table from `kwlist.h`.
//!
//! Lifted from `xtask/src/postgres/pgparse.rs` of tamnd/rudb at f5f7065a (spec/04 section 4.9).

use std::fmt::Write as _;
use std::path::Path;

use super::gram;
use super::lalr;

/// The header of each generated file.
fn header(what: &str, from: &str) -> String {
    format!(
        "//! {what}\n//!\n//! @generated by `cargo xtask sql` from {from}. Do not edit. `cargo xtask sql --check` runs in CI and fails if this file and the vendored files disagree.\n"
    )
}

/// Writes a static array of numbers, 16 to a line, out of the reach of rustfmt.
fn array<T: std::fmt::Display>(out: &mut String, doc: &str, name: &str, kind: &str, values: &[T]) {
    let _ = writeln!(
        out,
        "\n{doc}\n#[rustfmt::skip]\npub(crate) static {name}: [{kind}; {}] = [",
        values.len()
    );
    for chunk in values.chunks(16) {
        out.push_str("   ");
        for value in chunk {
            let _ = write!(out, " {value},");
        }
        out.push('\n');
    }
    out.push_str("];\n");
}

/// The Rust name of a token constant.
fn constant(name: &str) -> String {
    name.to_ascii_uppercase()
}

/// Writes `src/generated/tables.rs` from the text of `gram.y`.
pub(super) fn tables(texts: &[String]) -> Result<String, String> {
    let grammar = gram::read(&texts[0])?;
    let tables = lalr::tables(&grammar)?;
    let tokens = grammar.tokens;
    let mut out = header(
        "The LALR(1) tables of the PostgreSQL grammar, with the state numbers of `bison -v`.",
        "`vendor/postgres-19/src/backend/parser/gram.y`",
    );
    out.push_str(
        "//!\n//! An action row is read at `ACTION_BASE[state] + token` and a goto column at `GOTO_BASE[nonterminal] + state`. The entry in `ENTRIES` is the one there when `CHECK` has the same token or state, and the default otherwise. A row with the base `NO_BASE` has no entries.\n",
    );
    let _ = writeln!(
        out,
        "\n/// The number of tokens. A symbol below this number is a token.\npub const TOKENS: usize = {tokens};"
    );
    let _ =
        writeln!(out, "/// The number of states.\npub const STATES: usize = {};", tables.states);
    let _ = writeln!(
        out,
        "/// The number of rules. Rule 0 is `$accept`, which never reduces.\npub const RULES: usize = {};",
        grammar.rules.len()
    );
    let _ = writeln!(
        out,
        "/// The state after the end of the input. A shift into it accepts.\npub(crate) const FINAL: i16 = {};",
        tables.final_state
    );
    out.push_str(
        "/// The base of a row or a column with no entries.\npub(crate) const NO_BASE: i32 = i32::MIN;\n\
         /// The entry of an explicit error, which a `%nonassoc` token makes.\npub(crate) const ERROR: i16 = i16::MIN;\n",
    );

    let base = |b: &Option<i32>| b.map_or("NO_BASE".to_string(), |b| b.to_string());
    let action_base: Vec<String> = tables.action_base.iter().map(base).collect();
    array(
        &mut out,
        "/// The base of the action row of each state.",
        "ACTION_BASE",
        "i32",
        &action_base,
    );
    array(
        &mut out,
        "/// The rule each state reduces when its row has no entry for the token, or 0 for an error.",
        "DEFAULT_REDUCTION",
        "u16",
        &tables.default_reduction,
    );
    let goto_base: Vec<String> = tables.goto_base.iter().map(base).collect();
    array(
        &mut out,
        "/// The base of the goto column of each nonterminal, from `$accept`.",
        "GOTO_BASE",
        "i32",
        &goto_base,
    );
    array(
        &mut out,
        "/// The state each nonterminal goes to when its column has no entry for the state.",
        "DEFAULT_GOTO",
        "u16",
        &tables.default_goto,
    );
    array(
        &mut out,
        "/// The entries: a shift is the state, a reduction is minus the rule, a goto is the state.",
        "ENTRIES",
        "i16",
        &tables.table,
    );
    array(
        &mut out,
        "/// The token or the state of each entry, or -1 where there is no entry.",
        "CHECK",
        "i16",
        &tables.check,
    );
    let lhs: Vec<usize> = grammar.rules.iter().map(|r| r.lhs - tokens).collect();
    array(&mut out, "/// The nonterminal of each rule, from `$accept`.", "RULE_LHS", "u16", &lhs);
    let length: Vec<usize> = grammar.rules.iter().map(|r| r.rhs.len()).collect();
    array(
        &mut out,
        "/// The number of symbols on the right side of each rule.",
        "RULE_LENGTH",
        "u8",
        &length,
    );

    let _ = writeln!(
        out,
        "\n/// The name of each rule, as in `productions.txt`.\n#[rustfmt::skip]\npub(crate) static RULE_NAME: [&str; {}] = [",
        grammar.rules.len()
    );
    for rule in &grammar.rules {
        let _ = writeln!(out, "    {:?},", rule.name);
    }
    out.push_str("];\n");
    let _ = writeln!(
        out,
        "\n/// The name of each symbol, the tokens first.\n#[rustfmt::skip]\npub(crate) static SYMBOL_NAME: [&str; {}] = [",
        grammar.symbols.len()
    );
    for symbol in &grammar.symbols {
        let _ = writeln!(out, "    {symbol:?},");
    }
    out.push_str("];\n");

    // The tokens by name, and the tokens of the characters that the grammar uses.
    out.push_str(
        "\n/// The token numbers. A character token is in `CHARACTER`.\npub mod token {\n",
    );
    for (number, name) in grammar.symbols[..tokens].iter().enumerate() {
        if name.starts_with('\'') || name.starts_with('$') {
            continue;
        }
        let _ = writeln!(out, "    pub const {}: u16 = {number};", constant(name));
    }
    out.push_str("}\n");
    let mut characters = vec![0usize; 128];
    for (number, name) in grammar.symbols[..tokens].iter().enumerate() {
        let bytes = name.as_bytes();
        if bytes.len() == 3 && bytes[0] == b'\'' && bytes[2] == b'\'' {
            characters[bytes[1] as usize] = number;
        }
    }
    array(
        &mut out,
        "/// The token of each ASCII character that is a token by itself, or 0 for none.",
        "CHARACTER",
        "u16",
        &characters,
    );
    Ok(out)
}

/// One `PG_KEYWORD` line of `kwlist.h`.
struct Keyword {
    name: String,
    token: String,
    category: &'static str,
    bare: bool,
}

/// The number of buckets of the keyword hash. A power of two.
const BUCKETS: u32 = 256;
/// The number of slots of the keyword hash, as a power of two.
const SLOT_BITS: u32 = 10;

/// The hash of a word, with ASCII letters folded to lower case. The generated file has the same function, written out in `KEYWORD_HASH`.
fn hash(word: &[u8]) -> u32 {
    let mut h: u32 = 0x811c_9dc5;
    for &b in word {
        h ^= u32::from(b.to_ascii_lowercase());
        h = h.wrapping_mul(0x0100_0193);
    }
    h
}

/// The slot of a word with the hash `h` in a bucket with the displacement `d`.
fn slot(h: u32, d: u32) -> u32 {
    let mut x = h ^ d.wrapping_mul(0x9e37_79b9);
    x ^= x >> 16;
    x = x.wrapping_mul(0x85eb_ca6b);
    x ^= x >> 13;
    x = x.wrapping_mul(0xc2b2_ae35);
    x ^= x >> 16;
    x >> (32 - SLOT_BITS)
}

const KEYWORD_HASH: &str = "
/// The hash of a word, with ASCII letters folded to lower case, as PostgreSQL folds a keyword.
const fn hash(word: &[u8]) -> u32 {
    let mut h: u32 = 0x811c_9dc5;
    let mut at = 0;
    while at < word.len() {
        h ^= word[at].to_ascii_lowercase() as u32;
        h = h.wrapping_mul(0x0100_0193);
        at += 1;
    }
    h
}

/// The keyword that a word spells, with ASCII letters in any case, or `None`.
pub(crate) fn lookup(word: &[u8]) -> Option<&'static Keyword> {
    if word.len() > LONGEST {
        return None;
    }
    let h = hash(word);
    let d = u32::from(DISPLACEMENT[(h % BUCKETS) as usize]);
    let mut x = h ^ d.wrapping_mul(0x9e37_79b9);
    x ^= x >> 16;
    x = x.wrapping_mul(0x85eb_ca6b);
    x ^= x >> 13;
    x = x.wrapping_mul(0xc2b2_ae35);
    x ^= x >> 16;
    let index = SLOTS[(x >> (32 - SLOT_BITS)) as usize];
    if index == 0 {
        return None;
    }
    let keyword = &KEYWORDS[usize::from(index) - 1];
    keyword.name.as_bytes().eq_ignore_ascii_case(word).then_some(keyword)
}
";

/// Writes `src/generated/keywords.rs` from the text of `kwlist.h` and `gram.y`.
pub(super) fn keywords(texts: &[String]) -> Result<String, String> {
    let grammar = gram::read(&texts[1])?;
    let mut keywords = Vec::new();
    for (number, line) in texts[0].lines().enumerate() {
        let Some(rest) = line.strip_prefix("PG_KEYWORD(") else { continue };
        let bad = || format!("kwlist.h line {}: {line}", number + 1);
        let fields: Vec<&str> =
            rest.split_once(')').ok_or_else(bad)?.0.split(',').map(str::trim).collect();
        let [name, token, category, label] = fields[..] else { return Err(bad()) };
        let name = name.strip_prefix('"').and_then(|n| n.strip_suffix('"')).ok_or_else(bad)?;
        let category = match category {
            "UNRESERVED_KEYWORD" => "Unreserved",
            "COL_NAME_KEYWORD" => "ColumnName",
            "TYPE_FUNC_NAME_KEYWORD" => "TypeFuncName",
            "RESERVED_KEYWORD" => "Reserved",
            _ => return Err(bad()),
        };
        let bare = match label {
            "BARE_LABEL" => true,
            "AS_LABEL" => false,
            _ => return Err(bad()),
        };
        if !grammar.symbols[..grammar.tokens].iter().any(|s| s == token) {
            return Err(format!("kwlist.h names the token {token}, which gram.y does not have"));
        }
        keywords.push(Keyword { name: name.to_string(), token: token.to_string(), category, bare });
    }
    if keywords.windows(2).any(|w| w[0].name >= w[1].name) {
        return Err("the keywords of kwlist.h are not in order".to_string());
    }

    // The perfect hash: the words fall into buckets, and each bucket, the fullest first, gets the first displacement that puts all its words in free slots.
    let mut buckets: Vec<Vec<usize>> = vec![Vec::new(); BUCKETS as usize];
    for (index, keyword) in keywords.iter().enumerate() {
        buckets[(hash(keyword.name.as_bytes()) % BUCKETS) as usize].push(index);
    }
    let mut order: Vec<usize> = (0..buckets.len()).collect();
    order.sort_by_key(|&b| std::cmp::Reverse(buckets[b].len()));
    let mut slots = vec![0usize; 1 << SLOT_BITS];
    let mut displacement = vec![0u32; BUCKETS as usize];
    for bucket in order {
        if buckets[bucket].is_empty() {
            continue;
        }
        let found = (0..u32::from(u16::MAX)).find(|&d| {
            let mut taken: Vec<u32> = Vec::new();
            buckets[bucket].iter().all(|&k| {
                let at = slot(hash(keywords[k].name.as_bytes()), d);
                let free = slots[at as usize] == 0 && !taken.contains(&at);
                taken.push(at);
                free
            })
        });
        let d = found.ok_or("no displacement places the keywords of one bucket")?;
        for &k in &buckets[bucket] {
            slots[slot(hash(keywords[k].name.as_bytes()), d) as usize] = k + 1;
        }
        displacement[bucket] = d;
    }

    let mut out = header(
        "The keywords of PostgreSQL, with their tokens and categories.",
        "`vendor/postgres-19/src/include/parser/kwlist.h` and `gram.y`",
    );
    out.push_str(
        "//!\n//! A lookup is one perfect hash probe and one comparison. The words are in the order of `kwlist.h`, which is sorted.\n\
         \nuse super::tables::token;\n\
         \n/// The category that decides where a keyword can be a name.\n\
         #[derive(Clone, Copy, PartialEq, Eq, Debug)]\npub enum Category {\n    /// A name anywhere.\n    Unreserved,\n    /// A column name, and not a function or a type name.\n    ColumnName,\n    /// A function or a type name, and not a column name.\n    TypeFuncName,\n    /// Never a name.\n    Reserved,\n}\n\
         \n/// One keyword.\n#[derive(Debug)]\npub struct Keyword {\n    /// The word, in lower case.\n    pub name: &'static str,\n    /// The token that the lexer gives for it.\n    pub token: u16,\n    /// Where the word can be a name.\n    pub category: Category,\n    /// True when the word can be a column label without `AS`.\n    pub bare_label: bool,\n}\n",
    );
    out.push_str("\nuse Category::*;\n");
    let longest = keywords.iter().map(|k| k.name.len()).max().unwrap_or(0);
    let _ =
        writeln!(out, "\n/// The longest keyword.\npub(crate) const LONGEST: usize = {longest};");
    let _ = writeln!(out, "const BUCKETS: u32 = {BUCKETS};\nconst SLOT_BITS: u32 = {SLOT_BITS};");
    let _ = writeln!(
        out,
        "\n/// Every keyword.\n#[rustfmt::skip]\npub(crate) static KEYWORDS: [Keyword; {}] = [",
        keywords.len()
    );
    for k in &keywords {
        let _ = writeln!(
            out,
            "    Keyword {{ name: {:?}, token: token::{}, category: {}, bare_label: {} }},",
            k.name,
            constant(&k.token),
            k.category,
            k.bare
        );
    }
    out.push_str("];\n");
    array(&mut out, "/// The displacement of each bucket.", "DISPLACEMENT", "u16", &displacement);
    array(&mut out, "/// The keyword in each slot, from 1, or 0 for none.", "SLOTS", "u16", &slots);
    out.push_str(KEYWORD_HASH);
    Ok(out)
}

/// One array of the C file that bison writes, by its name.
fn c_array(c: &str, name: &str) -> Result<Vec<i64>, String> {
    let start = c.find(&format!(" {name}[] =")).ok_or(format!("bison wrote no {name}"))?;
    let body = &c[start..];
    let open = body.find('{').ok_or(format!("{name} has no body"))?;
    let close = body.find("};").ok_or(format!("{name} does not end"))?;
    body[open + 1..close]
        .split(',')
        .map(str::trim)
        .filter(|v| !v.is_empty())
        .map(|v| v.parse().map_err(|_| format!("{name} has the value {v}")))
        .collect()
}

/// One `#define` of the C file that bison writes.
fn c_define(c: &str, name: &str) -> Result<i64, String> {
    let at = c.find(&format!("#define {name} ")).ok_or(format!("bison wrote no {name}"))?;
    let value = c[at + name.len() + 8..].split_whitespace().next().unwrap_or("");
    value
        .trim_matches(|ch| ch == '(' || ch == ')')
        .parse()
        .map_err(|_| format!("{name} is {value}"))
}

/// Runs bison on `gram.rules` and compares its tables with the generated tables, entry by entry: the action of every state for every token and the goto of every state for every nonterminal.
pub(super) fn compare_with_bison(root: &Path, gram_y: &Path, rules: &Path) -> Result<(), String> {
    let gram =
        std::fs::read_to_string(gram_y).map_err(|e| format!("could not read gram.y: {e}"))?;
    let grammar = gram::read(&gram)?;
    let tables = lalr::tables(&grammar)?;
    let dir = root.join("target/sql-bison");
    std::fs::create_dir_all(&dir).map_err(|e| format!("could not make {}: {e}", dir.display()))?;
    let output = std::process::Command::new("bison")
        .arg("-o")
        .arg(dir.join("gram.c"))
        .arg(rules)
        .output()
        .map_err(|e| format!("could not run bison: {e}"))?;
    if !output.status.success() {
        return Err(format!("bison failed: {}", String::from_utf8_lossy(&output.stderr)));
    }
    let c = std::fs::read_to_string(dir.join("gram.c")).map_err(|e| format!("gram.c: {e}"))?;
    let pact = c_array(&c, "yypact")?;
    let defact = c_array(&c, "yydefact")?;
    let table = c_array(&c, "yytable")?;
    let check = c_array(&c, "yycheck")?;
    let pgoto = c_array(&c, "yypgoto")?;
    let defgoto = c_array(&c, "yydefgoto")?;
    let pact_ninf = c_define(&c, "YYPACT_NINF")?;
    let table_ninf = c_define(&c, "YYTABLE_NINF")?;
    let states = usize::try_from(c_define(&c, "YYNSTATES")?).unwrap_or(0);
    let tokens = usize::try_from(c_define(&c, "YYNTOKENS")?).unwrap_or(0);
    let rule_count = usize::try_from(c_define(&c, "YYNRULES")?).unwrap_or(0);
    let final_state = usize::try_from(c_define(&c, "YYFINAL")?).unwrap_or(0);
    let counts = (states, tokens, rule_count, final_state);
    let ours = (tables.states, grammar.tokens, grammar.rules.len(), tables.final_state);
    if counts != ours {
        return Err(format!(
            "bison makes (states, tokens, rules, final) {counts:?} and the generator {ours:?}"
        ));
    }

    // Bison numbers the rules from 1, so its rule n is rule n - 1 here.
    let lookup = |base: i64, at: usize, table: &[i64], check: &[i64]| -> Option<i64> {
        let index = usize::try_from(base + at as i64).ok()?;
        (check.get(index) == Some(&(at as i64))).then(|| table[index])
    };
    let our_table = widen(&tables.table);
    let our_check = widen(&tables.check);
    let mut differences = Vec::new();
    for state in 0..states {
        if state == final_state {
            continue;
        }
        for token in 0..tokens {
            let theirs = match (pact[state] != pact_ninf)
                .then(|| lookup(pact[state], token, &table, &check))
                .flatten()
            {
                Some(v) if v > 0 => v,
                Some(v) if v == 0 || v == table_ninf => 0,
                Some(v) => v + 1,
                None if defact[state] == 0 => 0,
                None => -(defact[state] - 1),
            };
            let ours = match tables.action_base[state]
                .and_then(|base| lookup(i64::from(base), token, &our_table, &our_check))
            {
                Some(v) if v == i64::from(i16::MIN) => 0,
                Some(v) => v,
                None => -i64::from(tables.default_reduction[state]),
            };
            if theirs != ours {
                differences.push(format!(
                    "state {state} token {}: bison {theirs}, ours {ours}",
                    grammar.symbols[token]
                ));
            }
        }
    }
    for nonterminal in 1..grammar.symbols.len() - tokens {
        for state in 0..states {
            let theirs =
                lookup(pgoto[nonterminal], state, &table, &check).unwrap_or(defgoto[nonterminal]);
            let ours = tables.goto_base[nonterminal]
                .and_then(|base| lookup(i64::from(base), state, &our_table, &our_check))
                .unwrap_or(i64::from(tables.default_goto[nonterminal]));
            if theirs != ours {
                differences.push(format!(
                    "goto {} from state {state}: bison {theirs}, ours {ours}",
                    grammar.symbols[tokens + nonterminal]
                ));
            }
        }
    }
    if !differences.is_empty() {
        let shown: Vec<&str> = differences.iter().take(20).map(String::as_str).collect();
        return Err(format!(
            "{} entries differ from bison\n  {}",
            differences.len(),
            shown.join("\n  ")
        ));
    }
    println!(
        "bison and the generator agree: {states} states, {tokens} tokens, {rule_count} rules, every action and every goto"
    );
    Ok(())
}

fn widen(values: &[i16]) -> Vec<i64> {
    values.iter().map(|&v| i64::from(v)).collect()
}
