[package]
name = "rupg-func"
description = "The 3,414 built-in functions, the 805 operators, the 249 casts, the aggregates and window functions, the regular expression engine."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
publish = false

[dependencies]
md-5.workspace = true
rupg-common.workspace = true
rupg-pgcatalog.workspace = true
rupg-sql.workspace = true
rupg-types.workspace = true

[lints]
workspace = true
